### ISSUE TITLE
Spike on extending the CLI to minimally support Senior Thesis restrictions spreadsheets

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#103]
This should use the Thesis Central Excel Spreadsheet as an input, and should also ensure that newly imported DSpace Items have the proper access policies applied within DataSpace.

Documentation *must* be considered a high priority for this.

**Comment by jrgriffiniii** [comment]
This would also provide an opportunity for working with the migrated DSpace development environment for JRuby procedure support and deployment.

**Comment by jrgriffiniii** [comment]
Much of https://github.com/pulibrary/dspace-cli/tree/master/seniorTheses will need to be removed and/or restructured.

**Comment by jrgriffiniii** [comment]
Much of this could be quickly prototyped using http://whatisthor.com/

**Comment by jrgriffiniii** [comment]
Perhaps https://github.com/weshatheleopard/rubyXL could be integrated for Spreadsheet parsing and reading/writing (please see https://spin.atomicobject.com/2017/03/22/parsing-excel-files-ruby/ for a blog post containing the benchmarks comparing Gems)

**Comment by jrgriffiniii** [comment]
https://github.com/caxlsx/caxlsx seems to be a well-maintained alternative with JRuby support.

**Comment by jrgriffiniii** [comment]
In order to advance https://github.com/pulibrary/dspace-development/issues/162, I have developed the following: https://github.com/pulibrary/dspace-cli/compare/master...pulibrary:jrgriffiniii-senior-theses-import

**Comment by kmcelwee** [comment]
Placing this in the icebox, assuming that the refactoring work this year will address this
