### ISSUE TITLE
Introduce YARD code documentation for dspace-cli

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#18]
This follows the work being undertaken for https://github.com/pulibrary/dspace-jruby/issues/2

**Comment by jrgriffiniii** [comment]
This is going to be delayed while the scripted procedures within dspace-cli are cleaned and evaluated. Hopefully only a minimal amount of YARD documentation will be required for these.

**Comment by kmcelwee** [comment]
This can be closed
