### ISSUE TITLE
Ensure that access to the Dataspace/OAR server infrastructure is granted for libkm

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#33]
This may require additional SN@P tickets (please see https://princeton.service-now.com/snap?sys_id=6793ae94db444c14a341de82ca961970&view=sp&id=ticket&table=incident)

**Comment by jrgriffiniii** [comment]
This was tested for production on the dataspace.princeton.edu and oar.princeton.edu production servers. I will proceed with requesting access for the following servers:

- updatespace.princeton.edu (10.6.48.231)
- oar-dev.princeton.edu (cisdr103l.princeton.edu)
- oawaiver.princeton.edu (asoar201l.princeton.edu)
- oawaiverdev.princeton.edu (asoar301l.princeton.edu)
- thesis-central.princeton.edu (libtc200l.aws.princeton.edu)
- thesis-central-qa.princeton.edu (libtc100l.aws.princeton.edu)

**Comment by jrgriffiniii** [comment]
Root access to updatespace was already granted to libkm, however the request for additional access was made using https://princeton.service-now.com/service?id=ticket&is_new_order=true&table=ticket&sys_id=311ae45d1b785810435885d56b4bcbcb

**Comment by kmcelwee** [comment]
All worked with the exception of `thesis-central.princeton.edu`. Opened a ticket with SN@P.

**Comment by kmcelwee** [comment]
Resolved along with #56
