### ISSUE TITLE
Create a user account with admin. privileges for libkm on oaworkflow.princeton.edu and oaworkflow-dev.princeton.edu (Symplectic Elements)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#47]
This will be necessary in order to begin documenting and testing the integration for this system with the Open Access Repository (OAR).

**Comment by kmcelwee** [comment]
`ssh -J libkm@epoxy.princeton.edu libkm@oaworkflow.princeton.edu` failed. Presumably this wasn't included when I gained admin permissions

**Comment by jrgriffiniii** [comment]
This account was successfully created on the production environment:

![image](https://user-images.githubusercontent.com/1443986/85410071-9de24500-b534-11ea-84df-f0beb6735c2f.png)

**Comment by jrgriffiniii** [comment]
This has been resolved for the QA environment as well:

![image](https://user-images.githubusercontent.com/1443986/85411151-fbc35c80-b535-11ea-8458-a1f4ca25e0d3.png)
