### ISSUE TITLE
Improve the statistics report generation

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#52]
These need not be automated for the 5.3 installation, but this should be a long-term goal. UI-facing

**Comment by jrgriffiniii** [comment]
Following the progress made on #68, it was discovered that the statistics.rb scripts needs to be updated on the server environment for the OAR.

**Comment by jrgriffiniii** [comment]
James found `/u/dspace/ruby/cli` (this was actually a git repository for `akinom/dspace-cli`) to contain a `statistics` directory on the server, and rebased the git repository from the `pulibrary/dspace-cli` `master` branch.

**Comment by jrgriffiniii** [comment]
Attempting to update the `dspace-cli` repository on the OAR QA environment (`oar-dev.princeton.edu`), the following discrepancy was found:

```
dspace@oar-qa-repo: master cli> git remote -v
origin  https://monikam@bitbucket.org/monikam/dspace-cli.git (fetch)
```

```
dspace@oar-prod-repo: master cli> git remote -v
origin  https://github.com/akinom/dspace-cli.git (fetch)
```

**Comment by jrgriffiniii** [comment]
The last commit for `dspace-cli` for the OAR QA environment dates from September 27th, 2017, leading me to believe that the OAR QA was perhaps not used often to test certain JRuby scripts.

**Comment by jrgriffiniii** [comment]
The last commit for `dspace-jruby` was logged at June 29th 2017 on the OAR QA environment.

**Comment by jrgriffiniii** [comment]
Testing and developing improvements for the statistics procedures can be run safely against the production database and Solr endpoint, as these are exclusively read-only operations.

**Comment by kmcelwee** [comment]
Atmire's Solr statistics utility, combined with the REST API and database queries have been successful at meeting stakeholder needs for the past year.
