### ISSUE TITLE
NetIDs are consistently set when new users are added to DSpace with `/dspace/bin/dspace user --add`

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#60]
This is currently the case for updatespace.princeton.edu:

```
dspace@updatespace: master ~> /dspace/bin/dspace user --list
id      email   netid   canLogin        surName givenName
2083    jrg5@princeton.edu      null    true    Griffin James
```

**Comment by kmcelwee** [comment]
In updatespace, this command had correctly parsed my info last week:
```
/dspace/bin/dspace user --add --email  kmcelwee@princeton.edu -g Kevin -s McElwee
```
When listing users, I'm seeing @jrgriffiniii 's info correctly output as:
```
2183	jrgriffiniii@gmail.com	jrgriffiniii	true	User	James
```
I assume we can close this issue?

**Comment by jrgriffiniii** [comment]
This is going to also be deprecated by our reliance upon Shibboleth for Single Sign-On support.
