### ISSUE TITLE
Prepare briefing for Atmire on essential custom functionality

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-cli#67]
Centralize documentation that provide Atmire with the custom features that are essential to our workflow. This will probably be a simple series of links to documentation already created by @jrgriffiniii. Finish preferably by Wednesday, May 27.

**Comment by kmcelwee** [comment]
Preferably by Wednesday, May 27, 2020

**Comment by kmcelwee** [comment]
@jrgriffiniii This was mentioned in earlier meetings. I assume Atmire doesn't really need this?

**Comment by jrgriffiniii** [comment]
Atmire has not explicitly requested this in past meetings, hence I'm going to close this.
