### ISSUE TITLE
Document how the DataSpace ingests student theses from Thesis Central (Vireo)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#7]
Currently there is a workflow structured for publishing content from the Vireo implementation Thesis Central (https://github.com/PrincetonUniversityLibrary/thesiscentral-vireo) and DataSpace. The tasks necessary for publishing these items should be documented, along with a general outline of the understanding between ITIMS and the Mudd Library regarding the regular archiving of student theses.

- [ ] Document the DSpace curation task "curate_senior_thesis_items"

**Comment by jrgriffiniii** [comment]
The scripts for this process are found within `/usr/local/DR/home/dspace/senior-thesis` on the dataspace.princeton.edu (production server environment)

**Comment by jrgriffiniii** [comment]
The scripts which are used to preprocess the Thesis Central (Vireo) data exports for the senior theses were implemented using Python, and these are found within the following directory: `/usr/local/DR/home/dspace/thesiscentral-vireo/dataspace` on dataspace.princeton.edu.

**Comment by jrgriffiniii** [comment]
This is also located in `/usr/local/DR/home/dspace/thesiscentral-vireo/dataspace` on updatespace.princeton.edu

**Comment by jrgriffiniii** [comment]
This should include a checklist outlining the steps involved in actually exporting the data from Thesis Central and importing these submissions as items into DataSpace.

**Comment by jrgriffiniii** [comment]
A draft of the proposed documentation has been published to https://gist.github.com/jrgriffiniii/60dbf718527a28820bca172ce4b2aaed

**Comment by jrgriffiniii** [comment]
This should also build off of the comments on https://github.com/pulibrary/dspace-development/issues/99

**Comment by kmcelwee** [comment]
In the past year, we seemed to have gotten our footing with this!
